services:
  todolist:
    image: todolist:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        endpoint: "${END_POINT}"  # Pega o valor de uma variável de ambiente
    ports:
      - "8000:8000"  # Expõe a porta 8000 do serviço todolist
    networks:
      - todolist

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Exponha a porta 80 para o host
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todolist
    depends_on:
      - todolist

networks:
  todolist:
    driver: bridge

