- hosts: ec2
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Adicionar a chave GPG do Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
        state: present

    - name: Atualizar pacotes apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Instalar Docker Compose V2
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present

    - name: Adicionar o usuário ubuntu ao grupo docker
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Verificar se o diretório do repositório existe
      ansible.builtin.stat:
        path: /home/ubuntu/todolist-IaC
      register: repo_directory

    - name: Clonar o repositório caso não exista
      ansible.builtin.git:
        repo: 'https://github.com/IgorAlanAlbuquerque/todolist-IaC.git'
        dest: '/home/ubuntu/todolist-IaC'
        version: main
      when: not repo_directory.stat.exists

    - name: Atualizar o repositório existente com git pull
      ansible.builtin.git:
        repo: 'https://github.com/IgorAlanAlbuquerque/todolist-IaC.git'
        dest: '/home/ubuntu/todolist-IaC'
        version: main
        update: yes
      when: repo_directory.stat.exists

    - name: Criar rede Docker 'todolist_net'
      community.docker.docker_network:
        name: todolist_net
        driver: bridge
      ignore_errors: yes  # Ignorar erro se a rede já existir

    - name: Definir variável de ambiente permanentemente
      lineinfile:
        path: /home/ubuntu/.bashrc  # ou você pode usar /etc/environment se for para todos os usuários
        line: 'export END_POINT="{{ rds_endpoint }}"'
        create: yes
      become: yes

    - name: Definir variável de ambiente e executar Docker compose up
      raw: |
        cd /home/ubuntu/todolist-IaC/docker/ && \
        docker compose up -d && \
        docker compose up -d
