- hosts: ec2
  remote_user: ubuntu
  become: true
  gather_facts: false

  tasks:
    - name: Atualizar pacotes e instalar dependências do Python e Ansible
      apt:
        update_cache: yes
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-apt
          - python-is-python3
          - python3-six
          - ansible
        state: present

    - name: Adicionar a chave GPG do Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Adicionar o usuário ubuntu ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clonar o repositório
      git:
        repo: 'https://github.com/IgorAlanAlbuquerque/todolist-IaaC.git'
        dest: '/home/ubuntu/todolist-IaaC'
        version: master

    - name: Definir variável de ambiente END_POINT no Docker Compose
      shell: "END_POINT={{ rds_endpoint }} docker compose up"
      args:
        chdir: /home/ubuntu/todolist-IaaC/docker/

