- hosts: ec2
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Adicionar a chave GPG do Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Adicionar o usuário ubuntu ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Verificar se o diretório do repositório existe
      stat:
        path: /home/ubuntu/todolist-IaaC
      register: repo_directory

    - name: Clonar o repositório caso não exista
      git:
        repo: 'https://github.com/IgorAlanAlbuquerque/todolist-IaaC.git'
        dest: '/home/ubuntu/todolist-IaaC'
        version: main
      when: not repo_directory.stat.exists

    - name: Atualizar o repositório existente com git pull
      command: git pull origin main
      args:
        chdir: /home/ubuntu/todolist-IaaC
      when: repo_directory.stat.exists

    - name: Definir a variável de ambiente END_POINT
      shell: "export END_POINT={{ rds_endpoint }}"

    - name: Fazer deploy da aplicação com Docker Compose
      shell: "docker compose up -d"
      args:
        chdir: /home/ubuntu/todolist-IaaC/docker/
